package nl.marcel.peakping

import android.content.Context
import java.nio.ByteBuffer
import java.nio.ByteOrder

/**
 * EGM96 geoid undulation lookup for any point on Earth.
 *
 * Converts WGS84 ellipsoidal altitude (what Android GPS reports) to
 * mean-sea-level (orthometric) height:
 *   h_msl = h_ellipsoidal - undulation(lat, lon)
 *
 * Data: egm96_1deg.bin — 181 × 361 grid of big-endian Int16 values in
 * centimetres, covering 90°N→90°S (row 0→180) and 0°E→360°E (col 0→360).
 * Generated by the downloadEgm96 Gradle task from NGA's WW15MGH.DAC.
 */
object GeoidModel {

    private const val ROWS = 181   // 90°N (row 0) to 90°S (row 180), 1° steps
    private const val COLS = 361   // 0°E (col 0) to 360°E (col 360), 1° steps
    private const val ASSET = "egm96_1deg.bin"

    private var grid: ShortArray? = null

    /** Call once from the ViewModel (or Application). */
    fun init(context: Context) {
        if (grid != null) return
        try {
            val bytes = context.assets.open(ASSET).use { it.readBytes() }
            val buf = ByteBuffer.wrap(bytes).order(ByteOrder.BIG_ENDIAN)
            grid = ShortArray(ROWS * COLS) { buf.short }
        } catch (_: Exception) {
            // Asset not present — undulation() will return 0 and altitude stays WGS84
        }
    }

    /**
     * Returns the EGM96 geoid undulation N in metres for the given WGS84
     * coordinates, using bilinear interpolation.
     * Returns 0.0 if the asset could not be loaded.
     */
    fun undulation(lat: Double, lon: Double): Double {
        val g = grid ?: return 0.0

        // Normalise longitude to [0, 360)
        val lon360 = ((lon % 360.0) + 360.0) % 360.0

        // Fractional grid indices (row 0 = 90°N)
        val rowF = 90.0 - lat
        val colF = lon360

        val r0 = rowF.toInt().coerceIn(0, ROWS - 2)
        val c0 = colF.toInt().coerceIn(0, COLS - 2)
        val r1 = r0 + 1
        val c1 = c0 + 1
        val dr = rowF - r0
        val dc = colF - c0

        // cm → m
        fun v(r: Int, c: Int) = g[r * COLS + c].toDouble() * 0.01

        return v(r0, c0) * (1 - dr) * (1 - dc) +
               v(r0, c1) * (1 - dr) * dc +
               v(r1, c0) * dr       * (1 - dc) +
               v(r1, c1) * dr       * dc
    }
}
